entityName: 'CrawlSite'
entity: 'MWSimple\CrawlSiteBundle\Entity\CrawlSite'
repository: 'MWSimpleCrawlSiteBundle:CrawlSite'
index: 'admin_crawlsite'
new: 'admin_crawlsite_new'
edit: 'admin_crawlsite_edit'
show: 'admin_crawlsite_show'
create: 'admin_crawlsite_create'
update: 'admin_crawlsite_update'
delete: 'admin_crawlsite_delete'
sessionFilter: 'CrawlSiteControllerFilter'
fieldsindex:
    a.id:
        name: 'Id'
        type: 'integer'
    a.site:
        name: 'Site'
        type: 'string'
    a.pattern:
        name: 'Pattern'
        type: 'string'
    a.active:
        name: 'Active'
        type: 'boolean'
    a.tags:
        name: 'Tags'
        type: 'ONE_TO_MANY'
fieldsshow:
    a.id:
        name: 'Id'
        type: 'integer'
    a.site:
        name: 'Site'
        type: 'string'
    a.pattern:
        name: 'Pattern'
        type: 'string'
    a.active:
        name: 'Active'
        type: 'boolean'
    a.tags:
        name: 'Tags'
        type: 'ONE_TO_MANY'