entityName: 'Tag'
entity: 'MWSimple\CrawlSiteBundle\Entity\Tag'
repository: 'MWSimpleCrawlSiteBundle:Tag'
index: 'admin_tag'
new: 'admin_tag_new'
edit: 'admin_tag_edit'
show: 'admin_tag_show'
create: 'admin_tag_create'
update: 'admin_tag_update'
delete: 'admin_tag_delete'
sessionFilter: 'TagControllerFilter'
fieldsindex:
    a.id:
        name: 'Id'
        type: 'integer'
    a.tag:
        name: 'Tag'
        type: 'string'
    a.field:
        name: 'Field'
        type: 'string'
    a.active:
        name: 'Active'
        type: 'boolean'
    a.site:
        name: 'Site'
        type: 'MANY_TO_ONE'
fieldsshow:
    a.id:
        name: 'Id'
        type: 'integer'
    a.tag:
        name: 'Tag'
        type: 'string'
    a.field:
        name: 'Field'
        type: 'string'
    a.active:
        name: 'Active'
        type: 'boolean'
    a.site:
        name: 'Site'
        type: 'MANY_TO_ONE'