<?php

namespace MWSimple\CrawlSiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CrawlSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrawlSiteRepository extends EntityRepository
{
}
